    
version: 2.1

commands:
  autotag:
    steps:
      - run: |
          make install-autotag
jobs:
  run-tests:
    docker:
    - image: ubuntu
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
            
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
  
      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up tests

  release-vesion:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - autotag
      - run:
          name: Tag Git Version
          command: make tag-version

workflows:
  version: 2
  build-deploy:
    jobs:
      - run-tests

      - release-vesion:
          requires:
            - run-tests
          filters:
            branches:
              only:
                - master